name: Node.js Package
on:
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
      # Checkout
      - uses: actions/checkout@v2
      # Setup node
      - uses: actions/setup-node@v2
        with:
          registry-url: 'https://npm.pkg.github.com'
      # Install dependencies
      - run: yarn install --frozen-lockfile
      # Test
      - run: yarn test
      # Build
      - run: yarn build
      # Publish to GitHub Packages
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}